// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvjwnYJLcpNTHb_YgjXUVoKvOfEYiODeg',
    appId: '1:975593935542:web:b09b04b5bec9dfb9dc0c17',
    messagingSenderId: '975593935542',
    projectId: 'guardianapp-9b94f',
    authDomain: 'guardianapp-9b94f.firebaseapp.com',
    storageBucket: 'guardianapp-9b94f.appspot.com',
    measurementId: 'G-SJVM052Y3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4HWAxex-_sX5lD4VQjvgox74Jz9_Re_k',
    appId: '1:975593935542:android:b1341baec632a0a6dc0c17',
    messagingSenderId: '975593935542',
    projectId: 'guardianapp-9b94f',
    storageBucket: 'guardianapp-9b94f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNYioXRuFsc10a6VCgH7_AnOVGol4m2is',
    appId: '1:975593935542:ios:b2efd1ade26f7135dc0c17',
    messagingSenderId: '975593935542',
    projectId: 'guardianapp-9b94f',
    storageBucket: 'guardianapp-9b94f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNYioXRuFsc10a6VCgH7_AnOVGol4m2is',
    appId: '1:975593935542:ios:f3cbc3d0dea4b7b9dc0c17',
    messagingSenderId: '975593935542',
    projectId: 'guardianapp-9b94f',
    storageBucket: 'guardianapp-9b94f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
